apiVersion: v1
kind: Secret
metadata: 
    name: mysql-secret
type: Opaque
data: 
    mysql-admin-password: Q2xhcnVzd2F5XzE=
    mysql-root-password: UjEyMzRy



# Clarusway_1 and R1234r to encode passwords first 
#echo -n 'R1234r' | base64   --->  Addressed as mysql-root-password in mysql-secret.yaml file
#echo -n 'CLarusway_1' | base64 ----> Addressed as mysql-admin-password in mysql-secret.yaml file

# Clarusway_1 and R1234r to decode passwords
# echo -n 'UjEyMzRy' | base64 --decode     ---> It gives root us poassword
# echo -n 'Q2xhcnVzd2F5XzE=' | base64 --decode   ---> It gives us admin password