AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an Linux EC2 with a security group that enables SSH connection.

Resources:
  MyLinuxEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - FirstSecurityGroup
      Tags:
        - Key: Name
          Value: MyLinux_ec2